import os

CLASSIFICATION_THRESHOLD = float(os.getenv("SEMANTIC_CLASSIFICATION_THRESHOLD", "0.60"))
FIELD_THRESHOLD = float(os.getenv("SEMANTIC_FIELD_THRESHOLD", "0.75"))
LLM_TIMEOUT = float(os.getenv("SEMANTIC_LLM_TIMEOUT", "30"))
LLM_ENDPOINT = os.getenv("SEMANTIC_LLM_ENDPOINT", "")
LLM_API_KEY = os.getenv("SEMANTIC_LLM_API_KEY", "")
LLM_MODEL = os.getenv("SEMANTIC_LLM_MODEL", "")
